replicaCount: 1

image:
  repository: 'luthiano/python-flask'
  tag: 52fd069f25182b927cd637212c2485a5686930ee
  pullPolicy: IfNotPresent

application:  "hostname-api"

autoscaling:
  minpods: 2
  maxpods: 10
  enabled: true


securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001

database:
  username: "aG9zdG5hbWVhcGk="
  password: "YzdMT2VEQjIwSVV1ZmZhTA=="
  host: mariadb


