replicaCount: 1

image:
  repository: 'luthiano/python-flask'
  tag: f2775f269a55a0de7bbf8d7d9e4965cc2058d75a
  pullPolicy: IfNotPresent

application:  "hostname-api"

autoscaling:
  minpods: 2
  maxpods: 10
  enabled: true

