replicaCount: 1

image:
  repository: 'luthiano/python-flask'
  tag: 1e0085d9c54c6f22b5c39c7b54f4d0cde2b397af
  pullPolicy: IfNotPresent

application:  "hostname-api"

autoscaling:
  minpods: 2
  maxpods: 10
  enabled: true

