replicaCount: 1

image:
  repository: 'luthiano/python-flask'
  tag: 2508dc383957634120aaf725683b07fe4229546a
  pullPolicy: IfNotPresent

application:  "hostname-api"

autoscaling:
  minpods: 2
  maxpods: 10
  enabled: true

