apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application }}
  labels: {{ .Values.application }}
spec:
  replicas: {{ .Values.replicaCount }} 
  spec:
    containers:
    - name: {{ .Chart.Name }} 
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      ports:
      - containerPort: 8080