apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application }}
  labels:
    app: {{ .Values.application }}
spec:
  {{- if .Values.securityContext.enabled }}
  securityContext:
    enabled: {{ .Values.securityContext.enabled }}
    runAsUser: {{ .Values.securityContext.runAsUser }}
    fsGroup: {{ .Values.securityContext.fsGroup }}
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.application }}
  template:
    metadata:
      labels:
        app: {{ .Values.application }}
    spec:
      containers:
      - name: {{ .Values.application }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: DATABASE_HOST
          value:  {{ .Values.database.host }}
        - name: DATABASE_USER_NAME
        valueFrom:
          secretKeyRef:
            name: {{ .Values.application }}
            key: USER_NAME
        - name: DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: {{ .Values.application }}
            key: PASSWORD
        ports:
        - containerPort: 8080
        resources:
         limits:
           cpu: 500m
         requests:
           cpu: 200m