kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.application }}
spec:
  selector:
    app: {{ .Values.application }}
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
    nodePort: 30002
  type: LoadBalancer